EducationApp/Controllers/SearchController.cs
using EducationApp.Lucene;
using EducationApp.Models;
using System;
using Lucene.Net.Analysis;
using Lucene.Net.Analysis.Standard;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Version = Lucene.Net.Util.Version;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Lucene.Net.Store;
using System.IO;
using Lucene.Net.Search;
using Lucene.Net.QueryParsers;
using System.Web.Mvc;
using EducationApp.Filters;

namespace EducationApp.Controllers
{
    [Unban]
    [Culture]
    public class SearchController : Controller
    {

        public ActionResult Index(string id)
        {
            List<Entry> findEntries = LuceneEntryModel.Search(id, null).ToList();
            return View(findEntries);
        }
    }
}

EducationApp/Views/Shared/CategoriesPartial.cshtml
<p>
    <br>
    <h4>@Resources.Resource.Search</h4>
    @using (@Html.BeginForm("Index", "Search", FormMethod.Get))
    {

        @Html.Editor("id", new { htmlAttributes = new { @class = "form-control" } });
    }
</p>

<hr>

<h4>@Resources.Resource.Categories</h4>
<div ng-controller="categoriesController">
    <div class="hline"></div>
    <div ng-repeat="category in categories">
        <p>
            <a href="../../View/ByCategory/{{category.id}}"><i class="fa fa-angle-right"></i> {{category.name}}</a>
        </p>
    </div>
</div>
<hr>

EducationApp/Views/Shared/EditView.cshtml
@model EducationApp.Models.UserDetailsViewModel

@{
    ViewBag.Title = @Resources.Resource.Manage;
}

<h2>@ViewBag.Title.</h2>

<div class="row" ng-app="myApp">
    <div class="col-md-4" ng-controller="avatarController" ng-init="getCurrentUserImage('@Model.UserId')">
        <div file-dropzone="[image/png, image/jpeg, image/gif]" file="image" imageup="imageUpdate()" data-max-file-size="3" class="avatar-drop-area">
            <img class="avatar-cropped" ng-src={{image}} />
        </div><br />
        <div ng-cloak ng-show="isNewImage && !isLoading" style="margin-left: 60px">
            <button class="btn btn-default" ng-click="sendImage('@Model.UserId')">Accept</button>
            <button class="btn btn-default" ng-click="getCurrentUserImage('@Model.UserId')">Reject</button>
        </div>
        <div ng-cloak ng-show="isLoading">
            <div class="progress progress-striped active" style="width: 264px;">
                <div class="progress-bar progress-bar-success"
                     aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 264px;">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">

        @using (Html.BeginForm("EditDetails", "Manage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Gender, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.HiddenFor(model => model.UserId, "@Model.UserId")
            <div class="form-group">
                @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Theme, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Language, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value=@Resources.Resource.Save class="btn btn-default" />
                </div>
            </div>

        }
    </div>

</div>

EducationApp/Views/Shared/EntriesCategoryPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-8">
                    <h4><strong><a href="#">Title of the post</a></strong></h4>

                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/260x180" alt="" class="img-responsive">
                    </a>

                </div>
                <div class="col-md-6">
                    <p>
                        Lorem ipsum dolor sit amet, id nec conceptam conclusionemque. Et eam tation
                        option. Utinam salutatus ex eum. Ne mea dicit tibique facilisi, ea mei
                        omittam explicari conclusionemque, ad nobis propriae quaerendum sea.
                    </p>
                    <p>
                        <a class="btn btn-default" href="#">Read more</a>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <p></p>
                    <p>
                        <i class="glyphicon glyphicon-user"></i> by <a href="#">Jeff</a> | <i class="glyphicon glyphicon-calendar"></i> Sept
                        16th, 2012 | <i class="glyphicon glyphicon-comment"></i>  <a href="#">3 Comments</a>
                        |
                        <i class="glyphicon glyphicon-share"></i> <a href="#">39 Shares</a>
                        | <i class="glyphicon glyphicon-tags"></i> Tags
                        : <a href="#"><span class="label label-info">Bootstrap</span></a>
                        <a href="#">
                            <span class="label label-info">UI</span>
                        </a>

                    </p>
                </div>
            </div>
        </div>
    </div>
    
</div>
<hr>

EducationApp/Views/Shared/PopularEntriesPartial.cshtml
    <h2 class="page-header">
        @Resources.Resource.HighestRating
    </h2>

<div ng-controller="popularEntriesController">


    <!-- /.row -->
    <!-- Project One -->
    <div ng-cloak infinite-scroll="loadMore()">
        <div ng-repeat="e in entries">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4><a href="../../view/index/{{e.Id}}">{{e.Title}}</a></h4><span ng-repeat="t in e.Tags"><a ng-href="../../View/ByTag/{{t | encodeUri}}" class="label label-primary">{{t}}</a> </span>

                                <hr />

                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-4">
                              
                                    <img ng-src="https://res.cloudinary.com/iedapp/image/upload/w_900,h_300,c_crop,c_fill/{{e.ImageId}}" alt="" class="img-responsive">
                               

                            </div>
                            <div class="col-md-8">
                                <p>
                                    {{e.Description}}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="panel-footer">
                        <i class="glyphicon glyphicon-user"></i> <a href="../../AccountUser/User/{{e.Username}}">{{e.Username}}</a> |
                        <i class="glyphicon glyphicon-time"></i> {{e.CreateTime}} |
                        <i class="glyphicon glyphicon-comment"></i> {{e.CommentsCount}} |
                        <i class="glyphicon glyphicon-star"></i> {{e.Rating}}
                    </div>
                </div>
            </div>
        </div>
</div>

EducationApp/Views/Shared/ResentEntriesPartial.cshtml
<div  ng-controller="homeController" ng-init="getEntries()">

    <div class="hline"></div>
    <ul class="popular-posts list-unstyled">
        <li class="row" ng-repeat="d in date">
            <div class="col-md-3">
                <a class="thumbnail" href="../../view/index/{{d.Id}}">
                    <img class="img-responsive" ng-src="https://res.cloudinary.com/iedapp/image/upload/w_900,h_300,c_crop,c_fill/{{d.ImageId}}" alt="Popular Post">
                </a>
            </div>
            <div class="col-md-9">
                <a href="../../view/index/{{d.Id}}">{{d.Title}}</a>
                <p>
                    <em class="small"><span class="glyphicon glyphicon-time"></span> {{d.CreateTime}}</em>
                </p>
            </div>
        </li>
    </ul>

    <hr>
</div>

EducationApp/Views/Shared/TagsCloudPartial.cshtml
    <div class="hline"></div>
    <div id="keyword_cloud" ng-controller="tagCloudCtrl">    
            <div class="dataBoxContent">
                <span ng-cloak ng-repeat="word in words">
<a href="../../view/bytag/{{word.TagName}}" class="cloud_{{ word.Weight }}">{{ word.TagName }}</a> </span>
            </div>   
     </div>           
    

EducationApp/Views/Shared/Template1.cshtml
<div class="form-group">
    <label class="control-label col-md-2">@Resources.Resource.Image</label>
    <div class="col-md-10">

        <div file-dropzone="[image/png, image/jpeg, image/gif]" file="$parent.image" data-max-file-size="3" class="bn-demowide">
            <img class="wide-cropped" ng-src={{image}} />
        </div>
    </div>

</div>

EducationApp/Views/Shared/Template2.cshtml
<div class="form-group">
    <label class="control-label col-md-2">@Resources.Resource.Image</label>
    <div class="col-md-10">

        <div file-dropzone="[image/png, image/jpeg, image/gif]" file="$parent.image" data-max-file-size="3" class="bn-demowide">
            <img class="wide-cropped" ng-src={{image}} />
        </div>
    </div>

</div>




<div class="form-group">
    <label class="control-label col-md-2">@Resources.Resource.Location</label>
    <div class="col-md-10">
        <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" events="map.events">
            <ui-gmap-marker coords="map.marker.coords" icon="map.marker.icon" idkey="map.marker.id"></ui-gmap-marker>
        </ui-gmap-google-map>
    </div>
</div>

EducationApp/Views/Shared/Template2Render.cshtml
@using System.Globalization
<div ng-app="myApp" ng-controller="viewController">

    <img class="img-responsive" ng-src="https://res.cloudinary.com/iedapp/image/upload/w_1200,h_240,c_crop,c_fill/@Model.ImageId" alt="">

    <marked>@Model.Content</marked>
    <ui-gmap-google-map center="{latitude:'@Model.Latitude.ToString(CultureInfo.InvariantCulture)',
                                longitude:'@Model.Longitude.ToString(CultureInfo.InvariantCulture)'}" zoom="11">
        <ui-gmap-marker idKey="{id:0}"
                        coords="{latitude:'@Model.Latitude.ToString(CultureInfo.InvariantCulture)',
                                longitude:'@Model.Longitude.ToString(CultureInfo.InvariantCulture)'}">
        </ui-gmap-marker>
    </ui-gmap-google-map>
</div>

EducationApp/Views/Shared/Template3.cshtml
<div class="form-group">
    <label class="control-label col-md-2">@Resources.Resource.Image</label>
    <div class="col-md-10">

        <div file-dropzone="[image/png, image/jpeg, image/gif]" file="$parent.image" data-max-file-size="3" class="bn-demo">
            <img class="center-cropped" ng-src={{image}} />
        </div>
    </div>

</div>

EducationApp/Views/Shared/Template3Render.cshtml
<div ng-app="myApp" ng-controller="viewController">
    <div class="container">
        <img class="leftimg" ng-src="https://res.cloudinary.com/iedapp/image/upload/w_300,h_300,c_crop,c_fill/@Model.ImageId" alt="">

        <marked>@Model.Content</marked>
    </div>
</div>

EducationApp/Views/Shared/Template4.cshtml
<div class="form-group">
    <label class="control-label col-md-2">@Resources.Resource.Image</label>
    <div class="col-md-10">

        <div file-dropzone="[image/png, image/jpeg, image/gif]" file="$parent.image" data-max-file-size="3" class="bn-demowide">
            <img class="wide-cropped" ng-src={{image}} />
        </div>
    </div>

</div>


<div class="form-group">
    <label class="control-label col-md-2">Youtube Link</label>
    <div class="col-md-10">
        <input ng-disabled="$parent.isUploading" class="form-control text-box single-line" type="text" value="" ng-model="$parent.link" required/>
    </div>
</div>

EducationApp/Views/Shared/Template4Render.cshtml
<div ng-app="myApp" ng-controller="viewController">
    <div ></div>
    <img class="img-responsive" ng-src="https://res.cloudinary.com/iedapp/image/upload/w_1200,h_240,c_crop,c_fill/@Model.ImageId" alt="">
    <marked>@Model.Content</marked>

    <div my-youtube code="'@Model.YoutubeLink'"></div>



</div>

EducationApp/Views/Shared/_Layout.cshtml
@using EducationApp.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/lodash.js"></script>
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/ng-infinite-scroll.js"></script>
    <script src="~/Scripts/angular-simple-logger.js"></script>
    <script src="~/Scripts/angular-google-maps.js"></script>
    <script src="~/Scripts/marked.js"></script>
    <script src="~/Scripts/ng-tags-input.js"></script>
    <script src="~/Scripts/angular-marked.min.js"></script>
    <script src="~/Scripts/app.js"></script>


    @if (Request.IsAuthenticated)
    {
        {
            ApplicationUser user = HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(HttpContext.Current.User.Identity.GetUserId());
            switch (user.Theme)
            {
                case Theme.Light:
                    {
                        <link href="~/Content/bootstrap.css" rel="stylesheet" id="stylesheet" />
                        break;
                    }
                case Theme.Dark:
                    {
                        <link href="~/Content/blackBootstrap.css" rel="stylesheet" id="stylesheet" />
                        break;
                    }
            }

        }
    }
    else
    {
        <link href="~/Content/bootstrap.css" rel="stylesheet" id="stylesheet" />
    }

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink(@Resources.Resource.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Resource.Home, "Index", "Home")</li>
                    <li>

                    </li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>